### ISSUE TITLE
Improved model management

### ISSUE THREAD

**Issue by jeffmaury** [projectatomic/ai-studio#172]
Here are the tasks required:

- [x] #43 
- [x] #201
- [x] https://github.com/projectatomic/ai-studio/issues/211
- [x] https://github.com/projectatomic/ai-studio/issues/332
- [x] https://github.com/projectatomic/ai-studio/issues/337
- [ ] #386
- [x] https://github.com/projectatomic/ai-studio/issues/384

**Comment by slemeur** [comment]
Closing this epic, as the remaining issue #386 is its own epic.
